keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  realm: my-tenant
  resource: tenant-app #client
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true

server:
  port: 8081